name: Go-Main

on:
    push:
        branches: ['main']
    pull_request:
        types: [opened, synchronize]
        branches: ['main']

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 1.22.3
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.3
      - name: Install dependencies
        run: |
          go get ./...
      - name: Build
        run: go build -v ./...
      - name: Run tests with coverage
        run: go test -coverprofile=coverage.out ./...
      - name: Generate HTML report
        run: go tool cover -html=coverage.out -o coverage.html
      - name: Upload Go test results
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.html
      - name: Run benchmarks
        run: go test ./... -bench=. -benchmem > benchmark.txt -timeout 99999s
      - name: Display benchmark results
        run: cat benchmark.txt
      - name: Upload benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: benchmark.txt
