name: Go-Develop

on:
    push:
        branches: ['develop']
    pull_request:
        types: [opened, synchronize]
        branches: ['develop']

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 1.22.3
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.3
      - name: Install dependencies
        run: |
          go get ./...
      - name: Build
        run: go build -v ./...
      - name: Run tests with coverage
        run: go test -coverprofile=coverage.out ./...
      - name: Generate HTML report
        run: go tool cover -html=coverage.out -o coverage.html
      - name: Upload Go test results
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.html
