name: Go

on:
    push:
        branches: ['main']
    pull_request:
        types: [opened, synchronize]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 1.21.5
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.5
          cache-dependency-path: ../../go.sum
      - name: Install dependencies
        run: |
          go get ./...
      - name: Build
        run: go build -v ./...
      - name: Test with the Go CLI
        run: go test -v -json ./... > TestResults.json
      - name: Display test results
        run: cat TestResults.json
      - name: Upload Go test results
        uses: actions/upload-artifact@v3
        with:
          name: Go-results
          path: TestResults.json
      - name: Run benchmarks
        run: go test ./... -bench=. -benchmem > benchmark.txt
      - name: Display benchmark results
        run: cat benchmark.txt
      - name: Upload benchmark results
        uses: actions/upload-artifact@v3
        with:
          name: benchmark-results
          path: benchmark.txt
